- project:
    templates:
      - build-openstack-docs-pti
    check:
      jobs:
        - openstack-tox-linters
    gate:
      jobs:
        - openstack-tox-linters
    promote:
      jobs:
        - promote-governance-sigs
